runtime: python37
entrypoint: gunicorn -b :$PORT wishlist.wsgi

handlers:
- url: /static
  static_dir: www/static

- url: /.*
  script: auto

env_variables:
  TRAVELER_PW: yvtTrtF3nkNpHix

beta_settings:
  cloud_sql_instances: wishlist-django-370319:us-central1:wishlist-db